/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedMessagesNewIndexRouteImport } from './routes/_authenticated/messages.new.index'
import { Route as AuthenticatedMessagesNewUserIdRouteImport } from './routes/_authenticated/messages.new.$userId'
import { Route as ApiPublicAuthGoogleCallbackRouteImport } from './routes/api/public/auth/google/callback'
import { Route as ApiPublicAuthGoogleStartRouteImport } from './routes/api/public/auth/google/start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesNewIndexRoute =
  AuthenticatedMessagesNewIndexRouteImport.update({
    id: '/messages/new/',
    path: '/messages/new/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesNewUserIdRoute =
  AuthenticatedMessagesNewUserIdRouteImport.update({
    id: '/messages/new/$userId',
    path: '/messages/new/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAuthGoogleCallbackRoute =
  ApiPublicAuthGoogleCallbackRouteImport.update({
    id: '/api/public/auth/google/callback',
    path: '/api/public/auth/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAuthGoogleStartRoute =
  ApiPublicAuthGoogleStartRouteImport.update({
    id: '/api/public/auth/google/start',
    path: '/api/public/auth/google/start',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/search': typeof SearchRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/me': typeof AuthenticatedMeRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/messages/new/$userId': typeof AuthenticatedMessagesNewUserIdRoute
  '/messages/new/': typeof AuthenticatedMessagesNewIndexRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
  '/api/public/auth/google/start': typeof ApiPublicAuthGoogleStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/search': typeof SearchRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/me': typeof AuthenticatedMeRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/messages/new/$userId': typeof AuthenticatedMessagesNewUserIdRoute
  '/messages/new': typeof AuthenticatedMessagesNewIndexRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
  '/api/public/auth/google/start': typeof ApiPublicAuthGoogleStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/search': typeof SearchRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/post/$id': typeof PostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/messages/new/$userId': typeof AuthenticatedMessagesNewUserIdRoute
  '/_authenticated/messages/new/': typeof AuthenticatedMessagesNewIndexRoute
  '/api/public/auth/google/callback': typeof ApiPublicAuthGoogleCallbackRoute
  '/api/public/auth/google/start': typeof ApiPublicAuthGoogleStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/search'
    | '/activity'
    | '/me'
    | '/post/$id'
    | '/u/$username'
    | '/messages/$conversationId'
    | '/messages/'
    | '/messages/new/$userId'
    | '/messages/new/'
    | '/api/public/auth/google/callback'
    | '/api/public/auth/google/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/search'
    | '/activity'
    | '/me'
    | '/post/$id'
    | '/u/$username'
    | '/messages/$conversationId'
    | '/messages'
    | '/messages/new/$userId'
    | '/messages/new'
    | '/api/public/auth/google/callback'
    | '/api/public/auth/google/start'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/auth-callback'
    | '/search'
    | '/_authenticated/activity'
    | '/_authenticated/me'
    | '/post/$id'
    | '/u/$username'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/messages/'
    | '/_authenticated/messages/new/$userId'
    | '/_authenticated/messages/new/'
    | '/api/public/auth/google/callback'
    | '/api/public/auth/google/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SearchRoute: typeof SearchRoute
  PostIdRoute: typeof PostIdRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicAuthGoogleCallbackRoute: typeof ApiPublicAuthGoogleCallbackRoute
  ApiPublicAuthGoogleStartRoute: typeof ApiPublicAuthGoogleStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/new/': {
      id: '/_authenticated/messages/new/'
      path: '/messages/new'
      fullPath: '/messages/new/'
      preLoaderRoute: typeof AuthenticatedMessagesNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/new/$userId': {
      id: '/_authenticated/messages/new/$userId'
      path: '/messages/new/$userId'
      fullPath: '/messages/new/$userId'
      preLoaderRoute: typeof AuthenticatedMessagesNewUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/auth/google/callback': {
      id: '/api/public/auth/google/callback'
      path: '/api/public/auth/google/callback'
      fullPath: '/api/public/auth/google/callback'
      preLoaderRoute: typeof ApiPublicAuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/google/start': {
      id: '/api/public/auth/google/start'
      path: '/api/public/auth/google/start'
      fullPath: '/api/public/auth/google/start'
      preLoaderRoute: typeof ApiPublicAuthGoogleStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedMessagesNewUserIdRoute: typeof AuthenticatedMessagesNewUserIdRoute
  AuthenticatedMessagesNewIndexRoute: typeof AuthenticatedMessagesNewIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedMessagesNewUserIdRoute: AuthenticatedMessagesNewUserIdRoute,
  AuthenticatedMessagesNewIndexRoute: AuthenticatedMessagesNewIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SearchRoute: SearchRoute,
  PostIdRoute: PostIdRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicAuthGoogleCallbackRoute: ApiPublicAuthGoogleCallbackRoute,
  ApiPublicAuthGoogleStartRoute: ApiPublicAuthGoogleStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
